language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lib-java' ]; then cd .. && eval "mv $currentfolder generator-lib-java" && cd generator-lib-java; fi
